[tools]
tree-sitter = "latest"

"npm:vscode-json-languageserver" = "latest"

lua-language-server = "latest"
stylua = "latest"

"npm:@typescript/native-preview" = "latest"
"npm:@tailwindcss/language-server" = "latest"
biome = "latest"

"pipx:ty" = "latest"
ruff = "latest"

zls = "0.15"
